### ISSUE TITLE
Inquiry about ndarrays_to_parameters_custom and parameters_to_ndarrays_custom functions

### ISSUE THREAD

**Issue by lhh1205** [elucidator8918/QFML-QF-2024#1]
Hello,

I've been studying your federated learning implementation and noticed the use of two custom functions: `ndarrays_to_parameters_custom` and `parameters_to_ndarrays_custom`. These functions seem to be crucial for handling parameter conversion, especially in the context of homomorphic encryption.

However, I couldn't find the definitions of these functions in the codebase. Could you please provide more information on:

1. Where are these functions defined in the project structure?
2. What is the exact implementation of these functions?
3. How do they differ from the standard Flower functions `ndarrays_to_parameters` and `parameters_to_ndarrays`?
4. Are there any specific requirements or dependencies for using these custom functions?

Understanding these custom implementations would greatly help in comprehending the overall flow of your federated learning system, especially regarding how it handles encrypted parameters.

Thank you for your time and assistance!

**Comment by lhh1205** [comment]
Hello,

I've found the definitions for ndarrays_to_parameters and parameters_to_ndarrays and understand their functions. I'm using Flower version 2.0.0, which I downloaded myself.

Since you haven't provided your custom Flower files, I'm unable to see the modifications you've made to flower/src/py/flwr/common/parameter.py. I'm very interested in understanding how you've customized these functions.

Would you be willing to share your definitions of these two functions? I would greatly appreciate it.

Thank you in advance for your help.

Best regards
![Snipaste_2024-08-06_21-36-20](https://github.com/user-attachments/assets/5f0dfdd7-ea03-4590-bd8a-0ea035bab399)
![Snipaste_2024-08-06_21-35-53](https://github.com/user-attachments/assets/1d4e942d-65fd-49a7-9a84-8d6f4550990e)

**Comment by elucidator8918** [comment]
Hello,

Please refer to this - https://gist.github.com/elucidator8918/388032951c421e28e3a0fbc20e827ccb

Best regards,
Siddhant

**Comment by lhh1205** [comment]
I apologize for bothering you again. I've been trying to run the FHE_FedQNN_CIFAR.ipynb file, and while it runs without errors, the training results are extremely poor. I'm not sure where the problem lies, but I instinctively suspect there might be an issue with the ray implementation in Flower. Below is my environment configuration. I would be immensely grateful if you could help me understand what might be causing this issue.
![Snipaste_2024-08-08_20-49-53](https://github.com/user-attachments/assets/816793b2-4832-4172-8481-745e6381337b)
![Snipaste_2024-08-08_20-46-30](https://github.com/user-attachments/assets/ef9c042b-ee15-4cf6-9f13-cc0c958a6b32)

**Comment by elucidator8918** [comment]
I don't see any issues with your training. It takes at least 20 rounds to achieve the results I got. The networks I used are quite basic, and you can make improvements to them. Since you are showing a good amount of interest in our work, I would be happy to learn more about you through your LinkedIn or portfolio.
